export enum Subject {
  Math = "mathematics",
  English = "english",
  History = "history",
  Geography = "geography",
  Physics = "physics",
  Chemistry = "chemistry",
  Biology = "biology",
  ComputerScience = "computerScience",
  SocialStudies = "socialStudies",
  JapaneseLanguage = "japaneseLanguage",
  ClassicalLiterature = "classicalLiterature",
  ClassicalChinese = "classicalChinese",
  Other = "other",
  NotSelected = "notSelected",
}
