export type Subject = 
  | "mathematics"
  | "english"
  | "history"
  | "geography"
  | "physics"
  | "chemistry"
  | "biology"
  | "computerScience"
  | "socialStudies"
  | "japaneseLanguage"
  | "classicalLiterature"
  | "classicalChinese"
  | "other"
  | "notSelected";
