export enum Subject {
  Math = "mathematics",
  English = "english",
  History = "history",
  Geography = "geography",
  Physics = "physics",
  Chemistry = "chemistry",
  Biology = "biology",
  ComputerScience = "computer_science",
  SocialStudies = "social_studies",
  ClassicalLiterature = "classical_literature",
  ClassicalChinese = "classicalChinese",
  JapaneseLanguage = "japaneseLanguage",
  NationalLanguage = "nationalLanguage",
  Other = "other",
  NotSelected = "notSelected",
}
