export const SECONDS_IN_MILLISECOND = 1000;
export const MINUTES_IN_MILLISECOND = SECONDS_IN_MILLISECOND * 60;
export const HOURS_IN_MILLISECOND = MINUTES_IN_MILLISECOND * 60;
export const DAYS_IN_MILLISECOND = HOURS_IN_MILLISECOND * 24;
export const YEARS_IN_MILLISECOND = DAYS_IN_MILLISECOND * 365;